all:
	/usr/local/arm/arm-2009q3/bin/arm-linux-gcc main.c  -o main_static.out -lmy_static_lib -L./my_static_lib -static
	/usr/local/arm/arm-2009q3/bin/arm-linux-gcc main.c  -o main_shared.out -lmy_static_lib -L./my_static_lib
